livery = {
	{"Mat: SA342_Camou_ADT_1", 0, "SA342_Camou_USMC_1_wx", false},
	{"Mat: SA342_Camou_ADT_1", 2, "SA342_Camou_USMC_1_spec", false},
	{"Mat: SA342_Camou_ADT_2", 0, "SA342_Camou_HMLA167_360_2_wx", false},
	{"camou_adt_2_droppable", 0, "SA342_Camou_HMLA167_360_2_wx", false},
	{"Mat: SA342_Camou_ADT_3", 0, "SA342_Camou_USMC_3_wx", false},
	{"Mat: SA342_Camou_ADT_4", 0, "SA342_Camou_USA_4.dds", true},
	{"Mat: SA342_Camou_ADT_5", 0, "SA342_Camou_USMC_5_wx", false},
	{"Mat: SA342_Camou_ADT_6", 0, "SA342_Camou_HMLA167_6_wx", false},
	{"Mat: SA342_Camou_ADT_7", 0, "SA342_Camou_USMC_7_wx", false},
	{"Mat: SA342_Camou_ADT_8", 0, "SA342_Camou_USMC_8_wx", false},
	{"Mat: SA342_Camou_ADT_9", 0, "SA342_Camou_USA_9.dds", true},
	{"Mat: SA342_Camou_ADT_10", 0, "SA342_Camou_USMC_10_wx", false},
	{"Mat: SA342_Camou_ADT_11", 0, "SA342_Camou_USMC_11_wx", false},
	{"cabin floor", 0, "SA342_Camou_USMC_11_wx", false},
	{"Mat: SA342_Camou_ADT_Wpns_1", 0, "SA342_Camou_USMC_Wpsns_1_wx", false},
	{"Mat: SA342_Camou_ADT_Wpns_2", 0, "SA342_Camou_USMC_Wpsns_2_wx", false},
	{"Mat: SA342_ADT_Addons", 0, "SA342_Camou_USMC_Addons_wx", false},
	{"Mat: SA342_ADT_Addons_2",0,"SA342_Camou_USMC_Addons_2_wx",false},
	{"Mat: SA342_Camou_ADT_Addons_3", 0, "SA342_Camou_USMC_Addons_3_wx", false},
	{"Mat: SA342_Cpit_Doors_1", 0, "SA342_Cpit_Doors_1_USMC.dds", false},
	{"Tex: SA342L_panels_Interiors_5", 0, "SA342L_panels_Interiors_5_USA.dds", true},
	{"Mat: SA342_panels_Interiors_7", 0, "SA342_panels_Interiors_7_USA.dds", true},
	{"sticks serial numbers 1", 0, "stick empty", true},
	{"sticks serial numbers 2", 0, "stick empty", true},
	{"sticks serial numbers 3", 0, "stick empty", true},
	{"sticks serial numbers 4", 0, "stick empty", true},
	{"front big letter stick 1", 0, "stick empty", true},
	{"front big letter stick 2", 0, "stick empty", true},
	{"right big letter 1", 0, "stick empty", true},
	{"right big letter 2", 0, "Serial_USN BlueGrey_wx", false},
	{"right big letter 3", 0, "Serial_USN BlueGrey_wx", false},
	{"left big letter 1", 0, "stick empty", true},
	{"left big letter 2", 0, "Serial_USN BlueGrey_wx", false},
	{"left big letter 3", 0, "Serial_USN BlueGrey_wx", false},
	{"sticks big letters", 0, "stick empty", true},
	{"bottom big letter 1", 0, "stick empty", true},
	{"bottom big letter 2", 0, "stick empty", true},
	{"bottom big letter 3", 0, "stick empty", true},
	{"serial_stick_left_1_GER", 0, "stick empty", true},
	{"serial_stick_left_2_GER", 0, "stick empty", true},
	{"serial_stick_left_3_GER", 0, "stick empty", true},
	{"serial_stick_left_4_GER", 0, "stick empty", true},
	{"serial_stick_right_1_GER", 0, "stick empty", true},
	{"serial_stick_right_2_GER", 0, "stick empty", true},
	{"serial_stick_right_3_GER", 0, "stick empty", true},
	{"serial_stick_right_4_GER", 0, "stick empty", true},
	{"right door big letter 1", 0, "stick empty", true},
	{"right door big letter 2", 0, "stick empty", true},
	{"right door big letter 3", 0, "stick empty", true},
	{"left door big letter 1", 0, "stick empty", true},
	{"left door big letter 2", 0, "stick empty", true},
	{"left door big letter 3", 0, "stick empty", true},
	{"left door big 3rd letter forward", 0, "stick empty", true},
	{"Mat: SA342_External_Decals",0,"SA342_External_decals_USMC_wx",false},
	
	{"Mat: SA342_Camou_ADT_HOT_LCHR_Wpsns_3",0,"SA342_Camou_USMC_HOT_LCHR_Wpsns_3_wx",false},

	{"2k_body",0,"2k_Body_HMLA167_des",false},
	{"2k_pilothelmet",0,"2k_helmet_marpat_des",false},
	{"2k_wsohelmettexture",0,"2k_helmet_marpat_des",false},
	{"2k_vest",0,"2k_vest_grn_wx",false},
	{"2k_shirt",0,"2k_shirt_USMC",false},
	{"2k_legs",0,"2k_legs_des",false},
	{"2k_hands",0,"2k_hand_brn",false},
	{"2k_shoes",0,"2k_shoe_des",false},
	{"2k_magbag",0,"2k_magbag_grn_wx",false},
	{"2k_bigbag",0,"2k_CHECKER_6_grn_wx",false},
	{"2k_bat_pilot",0,"2k_bat_n_more_HMLA167",false},
	{"2K_WSO_bat_cables",0,"2k_bat_n_more_HMLA167",false},	
--	{"2k_pilotmic",0,"2k_mic_blk",false},
--	{"2k_pilotmic",0,"2k_mic_blk",false},	
	
	----------------------------------------------------------------------------------------
	-- PBR
	----------------------------------------------------------------------------------------
	{"Mat: SA342_Camou_ADT_1", ROUGHNESS_METALLIC, "SA342_Camou_USMC_1_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_2", ROUGHNESS_METALLIC, "SA342_Camou_USMC_2_roughmet.dds", false},
	{"Mat: SA342_Damaged_Parts", ROUGHNESS_METALLIC, "SA342_Camou_USMC_2_roughmet.dds", false},
	{"camou_adt_2_droppable",  ROUGHNESS_METALLIC, "SA342_Camou_USMC_2_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_3", ROUGHNESS_METALLIC, "SA342_Camou_USMC_3_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_5", ROUGHNESS_METALLIC, "SA342_Camou_USMC_5_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_6", ROUGHNESS_METALLIC, "SA342_Camou_USMC_6_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_7", ROUGHNESS_METALLIC, "SA342_Camou_USMC_7_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_8", ROUGHNESS_METALLIC, "SA342_Camou_USMC_8_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_9", ROUGHNESS_METALLIC, "SA342_Camou_ADT_9_roughmet.dds", true},
	{"Mat: SA342_Camou_ADT_10", ROUGHNESS_METALLIC, "SA342_Camou_ADT_10_roughmet.dds", true},
	{"Mat: SA342_Camou_ADT_11", ROUGHNESS_METALLIC, "SA342_Camou_ADT_11_roughmet.dds", true},
	{"cabin floor", ROUGHNESS_METALLIC, "SA342_Camou_ADT_11_roughmet.dds", true},
	{"Mat: SA342_Cpit_Doors_1", ROUGHNESS_METALLIC, "SA342_Cpit_Doors_1_roughmet.dds", true},
		
	{"sticks serial numbers 1", ROUGHNESS_METALLIC, "empty", true},
	{"sticks serial numbers 2", ROUGHNESS_METALLIC, "empty", true},
	{"sticks serial numbers 3", ROUGHNESS_METALLIC, "empty", true},
	{"sticks serial numbers 4", ROUGHNESS_METALLIC, "empty", true},
	{"front big letter stick 1", ROUGHNESS_METALLIC, "empty", true},
	{"front big letter stick 2", ROUGHNESS_METALLIC, "empty", true},
	{"right big letter 1", ROUGHNESS_METALLIC, "empty", true},
	{"right big letter 2", ROUGHNESS_METALLIC, "Serial_Black.dds", true},
	{"right big letter 3", ROUGHNESS_METALLIC, "Serial_Black.dds", true},
	{"left big letter 1", ROUGHNESS_METALLIC, "empty", true},
	{"left big letter 2", ROUGHNESS_METALLIC, "Serial_Black.dds", true},
	{"left big letter 3", ROUGHNESS_METALLIC, "Serial_Black.dds", true},
	{"sticks big letters", ROUGHNESS_METALLIC, "empty", true},
	{"bottom big letter 1", ROUGHNESS_METALLIC, "empty", true},
	{"bottom big letter 2", ROUGHNESS_METALLIC, "empty", true},
	{"bottom big letter 3", ROUGHNESS_METALLIC, "empty", true},
	
	{"Damage_Parts ADT4", ROUGHNESS_METALLIC, "SA342_Camou_ADT_4_roughmet.dds", true},
	
	{"glass dam", ROUGHNESS_METALLIC, "Bulle_roughmet.dds", true},
	{"glass ext", ROUGHNESS_METALLIC, "Bulle_roughmet.dds", true},
	{"glass rear", ROUGHNESS_METALLIC, "glass_rear_roughmet.dds", true},
	{"lentille viviane", ROUGHNESS_METALLIC, "lentille viviane_roughmet.dds", true},
	{"Mat: SA342_lens_Optics", ROUGHNESS_METALLIC, "SA342_lens_Optics_roughmet.dds", true},			
	{"SA342_glass", ROUGHNESS_METALLIC, "glass_roughmet.dds", true},
	
	{"Mat: SA342_Camou_ADT_CPit_1", ROUGHNESS_METALLIC, "SA342_Camou_ADT_CPit_1_roughmet.dds", true},
	{"Mat: SA342_Camou_ADT_CPit_2", ROUGHNESS_METALLIC, "SA342_Camou_ADT_CPit_2_roughmet.dds", true},
	{"Mat: SA342_Camou_ADT_CPit_3", ROUGHNESS_METALLIC, "SA342_Camou_ADT_CPit_3_roughmet.dds", true},
	
	{"Mat: SA342_Cpit_Addons", ROUGHNESS_METALLIC, "SA342_Cpit_Addons_roughmet.dds", true},
		
	{"Mat: SA342_Camou_ADT_Wpns_1", ROUGHNESS_METALLIC, "SA342_Camou_ADT_Wpsns_1_roughmet.dds", true},
	{"Mat: SA342_Camou_ADT_Wpns_2", ROUGHNESS_METALLIC, "SA342_Camou_ADT_Wpsns_2_roughmet.dds", true},
	{"Mat: SA342_Camou_ADT_HOT_LCHR_Wpsns_3", ROUGHNESS_METALLIC, "SA342_Camou_ADT_HOT_LCHR_Wpsns_3_roughmet.dds", true},
	{"Mat: SA342_CockpitFrame_Addons", ROUGHNESS_METALLIC, "SA342_CockpitFrame_Addons_roughmet.dds", true},
	
	{"Mat: SA342_interior_weapon_Controls", ROUGHNESS_METALLIC, "SA342_interior_weapon_Controls_roughmet.dds", true},
	{"Mat: SA342_interior_weapon_terminal", ROUGHNESS_METALLIC, "SA342_interior_weapon_terminal_roughmet.dds", true},
		
	{"Mat: SA342_panels_Interior_Roof_Console", ROUGHNESS_METALLIC, "SA342_panels_Interior_Roof_Console_roughmet.dds", true},
	{"Mat: SA342_panels_Interior_Roof_Console_2", ROUGHNESS_METALLIC, "SA342_panels_Interior_Roof_Console_2_roughmet.dds", true},
	
	{"Mat: SA342_Controls", ROUGHNESS_METALLIC, "SA342_Controls_roughmet.dds", true},
	{"Mat: SA342_Controls_2", ROUGHNESS_METALLIC, "SA342_Controls_2_roughmet.dds", true},
	{"Mat: SA342_Controls_3", ROUGHNESS_METALLIC, "SA342_Controls_3_roughmet.dds", true},
	{"Mat: SA342_Controls_4_Addons", ROUGHNESS_METALLIC, "SA342_Controls_4_Addons_roughmet.dds", true},
	
	{"Mat: SA342_panels_Interiors", ROUGHNESS_METALLIC, "SA342_panels_Interiors_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_2", ROUGHNESS_METALLIC, "SA342_panels_Interiors_2_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_3", ROUGHNESS_METALLIC, "SA342_panels_Interiors_3_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_4", ROUGHNESS_METALLIC, "SA342_panels_Interiors_4_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_5", ROUGHNESS_METALLIC, "SA342_panels_Interiors_5_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_6", ROUGHNESS_METALLIC, "SA342_panels_Interiors_6_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_7", ROUGHNESS_METALLIC, "SA342_panels_Interiors_7_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_8", ROUGHNESS_METALLIC, "SA342_panels_Interiors_8_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_9", ROUGHNESS_METALLIC, "SA342_panels_Interiors_9_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_10", ROUGHNESS_METALLIC, "SA342_panels_Interiors_10_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_11", ROUGHNESS_METALLIC, "SA342_panels_Interiors_11_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_12", ROUGHNESS_METALLIC, "SA342_panels_Interiors_12_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_13", ROUGHNESS_METALLIC, "SA342_panels_Interiors_13_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_14", ROUGHNESS_METALLIC, "SA342_panels_Interiors_14_roughmet.dds", true},
	{"Mat: SA342_panels_Interiors_15", ROUGHNESS_METALLIC, "SA342_panels_Interiors_15_roughmet.dds", true},
	
	{"Mat: SA342_Rotorhead_1", ROUGHNESS_METALLIC, "SA342_Rotorhead_1_RoughMet.dds", true},
	{"Mat: SA342_Rotorhead_2", ROUGHNESS_METALLIC, "SA342_Rotorhead_2_roughmet.dds", true},
	{"Mat: SA342_Rotorhead_3", ROUGHNESS_METALLIC, "SA342_Rotorhead_3_roughmet.dds", true},
	{"Mat: SA342_Rotorhead_blades", ROUGHNESS_METALLIC, "SA342_Rotorhead_blades_roughmet.dds", true},
	{"Blades blurred", ROUGHNESS_METALLIC, "SA342_Blades_blurreds_roughmet.dds", true},
	{"Main rotor blades damages", ROUGHNESS_METALLIC, "SA342_Rotorhead_blades_roughmet.dds", true},
	
	{"Mat: SA342_Camou_ADT_Addons_2", ROUGHNESS_METALLIC, "SA342_Camou_ADT_Addons_2_roughmet.dds", true},
	{"Mat: SA342_ADT_Addons_2", ROUGHNESS_METALLIC, "SA342_Camou_ADT_Addons_2_roughmet.dds", true},
	
	{"Mat: turbine wire", ROUGHNESS_METALLIC, "SA342_parts_transp_roughmet.dds", true},
	{"Mat: SA342_parts_trans_2", ROUGHNESS_METALLIC, "SA342_parts_transp_2_roughmet.dds", true},
	{"Mat: SA342_Rear_Addons", ROUGHNESS_METALLIC, "SA342_Rear_Addons_roughmet.dds", true},
	
	{"Mat: SA342_switches_knobs", ROUGHNESS_METALLIC, "SA342_switches_knobs_roughmet.dds", true},
	{"Mat: SA342_Wool_Wire", ROUGHNESS_METALLIC, "SA342_Wool_wire_roughmet.dds", true},
	
	-- Damaged Tail, stabs
	{"damaged_droppable", ROUGHNESS_METALLIC, "SA342_Damaged_Parts_roughmet.dds", true},
	{"Damged_Parts", ROUGHNESS_METALLIC, "SA342_Damaged_Parts_roughmet.dds", true},
	{"Mat: SA342_Lights", ROUGHNESS_METALLIC, "SA342_lights_roughmet.dds", true},
	{"Pales blurred", ROUGHNESS_METALLIC, "Pales_Fennec Blurred_roughmet.dds", true},
	
	-- oblomok
	{"sol brule", ROUGHNESS_METALLIC, "sol brule_roughmet.dds", true},
	{"tole brulee", ROUGHNESS_METALLIC, "tole brulee_roughmet.dds", true},
	
	-- FAS
	{"Mat: SA342_ADT_Addons", ROUGHNESS_METALLIC, "SA342_Camou_ADT_Addons_roughmet.dds", true},
	
	--HOT3
	{"Mat: SA342_HOT3", ROUGHNESS_METALLIC, "SA342_HOT_roughmet.dds", true},
	
	-- HOT3 tubes
	{"Mat: SA342_Weapons", ROUGHNESS_METALLIC, "SA342_Weapons_roughmet.dds", true},
	
	-- IR Deflector
	{"Mat: SA342_Camou_ADT_Addons_3", ROUGHNESS_METALLIC, "SA342_Camou_ADT_Addons_3_roughmet.dds", true},
}
name = 'HVY 48TH GAZ'
countries = {"USA"}